name: Build

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint
